upload problems 121 ~ 132

diff --git a/java/scripts/parse b/java/scripts/parse
--- a/java/scripts/parse
+++ b/java/scripts/parse
@@ -15,32 +15,28 @@ SED_SCRIPT="parse.sed"
 AWK_SCRIPT="join.awk"
 DEST="leetcode.tsv"
 
-if !(test -s "$DEST")
-then
-    # crawl from leetcode algorithms page
-    if !(test -s "$WEBFILE")
-    then 
-        curl "$WEBURL" > "$WEBFILE"
-    fi    
+# crawl from leetcode algorithms page
+curl "$WEBURL" > "$WEBFILE"
 
-    # parse webpage and generate csv file
-    if !(test -s "$SED_SCRIPT")
-    then
-        echo "sed file not found!">&2
-        exit 1
-    fi
-    if !(test -s "$AWK_SCRIPT")
-    then
-        echo "awk file not found!">&2
-        exit 1
-    fi
-    sed -f "$SED_SCRIPT" "$WEBFILE" | awk -f "$AWK_SCRIPT" | sort -k1,1n > "$DEST"
+# parse webpage and generate tsv file
+if !(test -s "$SED_SCRIPT")
+then
+    echo "sed file not found!">&2
+    exit 1
+fi
+if !(test -s "$AWK_SCRIPT")
+then
+    echo "awk file not found!">&2
+    exit 1
 fi
 
-#clean up
-#if (test -s "$WEBFILE")
-#then
-    #rm "$WEBFILE"
-#fi
+# sort by problem's number
+sed -f "$SED_SCRIPT" "$WEBFILE" | awk -f "$AWK_SCRIPT" | sort -k1,1n > "$DEST"
+
+# clean up
+if (test -s "$WEBFILE")
+then
+rm "$WEBFILE"
+fi
 
 echo "Succeed! Check out file -> $DEST"
